/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy profile cá nhân (1 record duy nhất) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["Profile"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy thông tin học vấn */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["Education"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách kỹ năng theo category */
        get: {
            parameters: {
                query?: {
                    locale?: components["parameters"]["LocaleQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                categories?: components["schemas"]["SkillCategory"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách kinh nghiệm làm việc */
        get: {
            parameters: {
                query?: {
                    locale?: components["parameters"]["LocaleQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                experiences?: components["schemas"]["Experience"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách dự án (published) */
        get: {
            parameters: {
                query?: {
                    locale?: components["parameters"]["LocaleQuery"];
                    category?: "web" | "mobile" | "fullstack";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                projects?: components["schemas"]["ProjectListItem"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết dự án */
        get: {
            parameters: {
                query?: {
                    locale?: components["parameters"]["LocaleQuery"];
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["ProjectDetail"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách bài viết (pagination) */
        get: {
            parameters: {
                query?: {
                    locale?: components["parameters"]["LocaleQuery"];
                    page?: number;
                    limit?: number;
                    tag?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                posts?: components["schemas"]["BlogPostListItem"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết bài viết */
        get: {
            parameters: {
                query?: {
                    locale?: components["parameters"]["LocaleQuery"];
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["BlogPost"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gửi tin nhắn liên hệ */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContactCreateInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                /** @example Tin nhắn đã được gửi thành công. */
                                message?: string;
                            };
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập section Nhật */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["TokenPair"];
                        };
                    };
                };
                401: components["responses"]["InvalidPassword"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất (client drop token; endpoint để symmetry) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                /** @example Đã đăng xuất */
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy bộ Hiragana + Katakana đầy đủ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                hiragana?: components["schemas"]["Kana"][];
                                katakana?: components["schemas"]["Kana"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/quiz/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nộp kết quả quiz kana */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitKanaAttemptInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["KanaAttemptResult"];
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiến độ học kana */
        get: {
            parameters: {
                query?: {
                    quizType?: "hiragana" | "katakana" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["KanaProgress"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/progress/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thống kê kana (alias của /japanese/progress không filter) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["KanaProgress"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/minna/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách bài Minna no Nihongo (50 bài) */
        get: {
            parameters: {
                query?: {
                    book?: 1 | 2;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                lessons?: components["schemas"]["VocabLessonSummary"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/minna/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết bài Minna + toàn bộ từ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    lessonId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["VocabLessonDetail"];
                        };
                    };
                };
                404: components["responses"]["LessonNotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/minna/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nộp kết quả bài tập Minna */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitVocabAttemptInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["VocabAttemptResult"];
                        };
                    };
                };
                404: components["responses"]["LessonNotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/minna/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiến độ học Minna */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["VocabProgress"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/numbers/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách bài số đếm (3 bài) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                lessons?: components["schemas"]["VocabLessonSummary"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/numbers/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết bài số đếm + từ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    lessonId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["VocabLessonDetail"];
                        };
                    };
                };
                404: components["responses"]["LessonNotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/numbers/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nộp kết quả bài tập số đếm */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitVocabAttemptInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["VocabAttemptResult"];
                        };
                    };
                };
                404: components["responses"]["LessonNotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/japanese/numbers/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiến độ học số đếm */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["VocabProgress"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập admin */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["TokenPair"];
                        };
                    };
                };
                401: components["responses"]["InvalidCredentials"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất admin */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cập nhật profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: components["schemas"]["Profile"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dự án (kể cả unpublished, bao gồm mọi translation) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Tạo dự án */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectCreateInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cập nhật dự án */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectCreateInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Xoá dự án */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects/{id}/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert translation cho 1 locale */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectTranslationInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo kinh nghiệm */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExperienceCreateInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExperienceCreateInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiences/{id}/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExperienceTranslationInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/skills/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        i18nKey: string;
                        sortOrder?: number;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/skills/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/skills/categories/{id}/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        locale: string;
                        name: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        categoryId: string;
                        name: string;
                        sortOrder?: number;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/skills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Education"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/education/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Education"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/blog/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bài viết (kể cả chưa publish) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Tạo bài viết */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BlogPostCreateInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                slug?: string;
                                readingTime?: number;
                            };
                        };
                    };
                };
                409: components["responses"]["SlugConflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/blog/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BlogPostCreateInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contact-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách tin nhắn liên hệ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"] & {
                            data?: {
                                messages?: components["schemas"]["ContactMessage"][];
                                unreadCount?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contact-messages/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Đánh dấu đã đọc / chưa đọc */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        read: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/contact-messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Success: {
            /** @enum {boolean} */
            success: true;
            data: unknown;
        };
        Error: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @enum {string} */
                code: "INVALID_PASSWORD" | "INVALID_CREDENTIALS" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "POST_NOT_FOUND" | "LESSON_NOT_FOUND" | "VALIDATION_ERROR" | "INVALID_EXERCISE_TYPE" | "SLUG_CONFLICT" | "INTERNAL_ERROR";
                message: string;
                fields?: {
                    [key: string]: string;
                };
            };
        };
        Pagination: {
            total?: number;
            page?: number;
            limit?: number;
            totalPages?: number;
        };
        /**
         * @example {
         *       "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMtMTIzIiwicm9sZSI6ImphcGFuZXNlIiwidHlwZSI6ImphcGFuZXNlIiwiaWF0IjoxNzY5MzMwMDAwLCJleHAiOjE3Njk0MTY0MDB9.signature",
         *       "expiresAt": "2026-04-25T10:30:00.000Z"
         *     }
         */
        TokenPair: {
            /** @description JWT */
            token: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /**
         * @example {
         *       "name": "Hà Duy Hùng",
         *       "title": "Frontend Developer",
         *       "email": "haduyhungdz123@gmail.com",
         *       "phone": "+84 353 087 299",
         *       "location": "Hà Nội, Việt Nam",
         *       "dateOfBirth": "05-10-2000",
         *       "socialLinks": {
         *         "github": "https://github.com/haduyhung",
         *         "facebook": "https://facebook.com/haduyhungdz",
         *         "email": "mailto:haduyhungdz123@gmail.com"
         *       }
         *     }
         */
        Profile: {
            name?: string;
            title?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            location?: string;
            dateOfBirth?: string;
            socialLinks?: {
                [key: string]: string;
            };
        };
        /**
         * @example {
         *       "id": "5b2e7a9d-1c4f-4b8e-9a3d-2f1c8e7d6b5a",
         *       "school": "Học viện Kỹ thuật Mật mã",
         *       "major": "Công nghệ thông tin",
         *       "startYear": "2020",
         *       "endYear": "2024",
         *       "status": "Tốt nghiệp"
         *     }
         */
        Education: {
            /** Format: uuid */
            id?: string;
            school?: string;
            major?: string;
            startYear?: string;
            endYear?: string;
            status?: string;
        };
        /**
         * @example {
         *       "id": "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
         *       "name": "Frontend",
         *       "skills": [
         *         "React",
         *         "Next.js",
         *         "TypeScript",
         *         "JavaScript",
         *         "HTML/CSS",
         *         "Tailwind CSS"
         *       ]
         *     }
         */
        SkillCategory: {
            /** Format: uuid */
            id?: string;
            /** @description Đã flatten theo locale */
            name?: string;
            skills?: string[];
        };
        /**
         * @example {
         *       "id": "9f8e7d6c-5b4a-3c2d-1e0f-9a8b7c6d5e4f",
         *       "company": "Katech",
         *       "period": "2023 - Present",
         *       "techStack": [
         *         "React",
         *         "TypeScript",
         *         "Next.js",
         *         "NestJS"
         *       ],
         *       "role": "Frontend Developer",
         *       "description": "Phát triển sản phẩm web cho khách hàng quốc tế.",
         *       "responsibilities": [
         *         "Thiết kế và triển khai UI bằng React + Tailwind",
         *         "Tích hợp REST API & GraphQL",
         *         "Code review, mentor 2 junior developers"
         *       ]
         *     }
         */
        Experience: {
            /** Format: uuid */
            id?: string;
            company?: string;
            period?: string;
            techStack?: string[];
            role?: string;
            description?: string;
            responsibilities?: string[];
        };
        ExperienceCreateInput: {
            company: string;
            period: string;
            techStack: string[];
            sortOrder?: number;
        };
        ExperienceTranslationInput: {
            locale: string;
            role: string;
            description: string;
            responsibilities: string[];
        };
        /**
         * @example {
         *       "id": "abc12345-6789-0def-1234-567890abcdef",
         *       "slug": "lets-goo",
         *       "category": "web",
         *       "company": "Katech",
         *       "period": "2023 - Present",
         *       "teamSize": 5,
         *       "techStack": [
         *         "React",
         *         "TypeScript",
         *         "Next.js"
         *       ],
         *       "title": "Let's Goo",
         *       "description": "Nền tảng đặt tour du lịch online.",
         *       "highlights": [
         *         "Tích hợp Stripe + VNPay",
         *         "i18n cho 4 ngôn ngữ",
         *         "PWA hỗ trợ offline"
         *       ]
         *     }
         */
        ProjectListItem: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            category?: string;
            company?: string;
            period?: string;
            teamSize?: number | null;
            techStack?: string[];
            title?: string;
            description?: string;
            highlights?: string[];
        };
        ProjectDetail: components["schemas"]["ProjectListItem"] & {
            longDescription?: string;
            responsibilities?: string[];
        };
        ProjectCreateInput: {
            slug: string;
            /** @enum {string} */
            category: "web" | "mobile" | "fullstack";
            company: string;
            period: string;
            teamSize?: number;
            techStack: string[];
            sortOrder?: number;
            published?: boolean;
        };
        ProjectTranslationInput: {
            locale: string;
            title: string;
            description: string;
            longDescription: string;
            highlights: string[];
            responsibilities: string[];
        };
        /**
         * @example {
         *       "id": "11223344-5566-7788-99aa-bbccddeeff00",
         *       "slug": "react-server-components-explained",
         *       "locale": "vi",
         *       "title": "React Server Components — bản chất và khi nào nên dùng",
         *       "description": "Phân tích RSC từ góc nhìn đã làm production trong 6 tháng.",
         *       "tags": [
         *         "react",
         *         "nextjs",
         *         "performance"
         *       ],
         *       "publishedAt": "2026-04-01",
         *       "readingTime": 8
         *     }
         */
        BlogPostListItem: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            locale?: string;
            title?: string;
            description?: string;
            tags?: string[];
            /** Format: date */
            publishedAt?: string;
            readingTime?: number;
        };
        BlogPost: components["schemas"]["BlogPostListItem"] & {
            /** @description MDX content */
            content?: string;
        };
        BlogPostCreateInput: {
            slug: string;
            /** @enum {string} */
            locale: "en" | "vi" | "ja" | "fr";
            title: string;
            description: string;
            content: string;
            tags: string[];
            published?: boolean;
            /** Format: date */
            publishedAt: string;
            readingTime: number;
        };
        /**
         * @example {
         *       "name": "Nguyễn Văn A",
         *       "email": "vana@example.com",
         *       "subject": "Cơ hội hợp tác freelance",
         *       "message": "Chào Hùng, mình muốn trao đổi về một dự án Next.js cho team mình..."
         *     }
         */
        ContactCreateInput: {
            name: string;
            /** Format: email */
            email: string;
            subject: string;
            message: string;
        };
        ContactMessage: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: email */
            email?: string;
            subject?: string;
            message?: string;
            read?: boolean;
            /** Format: date-time */
            sentAt?: string;
        };
        /**
         * @example {
         *       "char": "し",
         *       "romaji": [
         *         "shi",
         *         "si"
         *       ],
         *       "row": "s",
         *       "col": 1
         *     }
         */
        Kana: {
            char?: string;
            romaji?: string[];
            row?: string;
            col?: number;
        };
        /**
         * @example {
         *       "quizType": "hiragana",
         *       "mode": "kana",
         *       "score": 38,
         *       "total": 46,
         *       "answers": [
         *         {
         *           "character": "あ",
         *           "romaji": "a",
         *           "userAnswer": "a",
         *           "correct": true
         *         },
         *         {
         *           "character": "し",
         *           "romaji": "shi",
         *           "userAnswer": "si",
         *           "correct": true
         *         },
         *         {
         *           "character": "ち",
         *           "romaji": "chi",
         *           "userAnswer": "ki",
         *           "correct": false
         *         }
         *       ]
         *     }
         */
        SubmitKanaAttemptInput: {
            /** @enum {string} */
            quizType: "hiragana" | "katakana";
            /** @enum {string} */
            mode: "kana" | "romaji";
            score: number;
            total: number;
            answers: {
                character: string;
                romaji: string;
                userAnswer: string;
                correct: boolean;
            }[];
        };
        /**
         * @example {
         *       "attemptId": "fe9d8c7b-6a5b-4c3d-2e1f-0a9b8c7d6e5f",
         *       "score": 38,
         *       "total": 46,
         *       "accuracy": 82.6,
         *       "weakCharacters": [
         *         "ち",
         *         "つ",
         *         "ふ"
         *       ]
         *     }
         */
        KanaAttemptResult: {
            /** Format: uuid */
            attemptId?: string;
            score?: number;
            total?: number;
            /** @description Percent with 1 decimal, e.g. 82.6 */
            accuracy?: number;
            weakCharacters?: string[];
        };
        /**
         * @example {
         *       "summary": {
         *         "hiragana": {
         *           "masteredCount": 32,
         *           "totalCount": 46,
         *           "masteryPercent": 69.6,
         *           "totalAttempts": 5
         *         },
         *         "katakana": {
         *           "masteredCount": 10,
         *           "totalCount": 46,
         *           "masteryPercent": 21.7,
         *           "totalAttempts": 2
         *         }
         *       },
         *       "weakCharacters": [
         *         {
         *           "character": "ち",
         *           "quizType": "hiragana",
         *           "correctCount": 1,
         *           "attemptCount": 5,
         *           "accuracy": 20
         *         },
         *         {
         *           "character": "ツ",
         *           "quizType": "katakana",
         *           "correctCount": 0,
         *           "attemptCount": 3,
         *           "accuracy": 0
         *         }
         *       ],
         *       "recentAttempts": [
         *         {
         *           "id": "11..",
         *           "quizType": "hiragana",
         *           "mode": "kana",
         *           "score": 38,
         *           "total": 46,
         *           "attemptedAt": "2026-04-24T10:30:00Z"
         *         },
         *         {
         *           "id": "22..",
         *           "quizType": "katakana",
         *           "mode": "romaji",
         *           "score": 21,
         *           "total": 46,
         *           "attemptedAt": "2026-04-23T18:11:00Z"
         *         }
         *       ]
         *     }
         */
        KanaProgress: {
            summary?: {
                [key: string]: {
                    masteredCount?: number;
                    totalCount?: number;
                    masteryPercent?: number;
                    totalAttempts?: number;
                };
            };
            weakCharacters?: {
                character?: string;
                /** @enum {string} */
                quizType?: "hiragana" | "katakana";
                correctCount?: number;
                attemptCount?: number;
                accuracy?: number;
            }[];
            recentAttempts?: {
                /** Format: uuid */
                id?: string;
                quizType?: string;
                mode?: string;
                score?: number;
                total?: number;
                /** Format: date-time */
                attemptedAt?: string;
            }[];
        };
        VocabMeaning: {
            en?: string | null;
            fr?: string | null;
            vi?: string | null;
        };
        /**
         * @example {
         *       "id": "aa11bb22-cc33-dd44-ee55-ff6677889900",
         *       "wordIndex": 1,
         *       "edition": [
         *         1,
         *         2
         *       ],
         *       "kanji": null,
         *       "kana": "わたし",
         *       "romaji": "watashi",
         *       "meaning": {
         *         "en": "I",
         *         "fr": "je, moi",
         *         "vi": "tôi"
         *       }
         *     }
         */
        VocabWord: {
            /** Format: uuid */
            id?: string;
            wordIndex?: number;
            edition?: number[];
            kanji?: string | null;
            kana?: string;
            romaji?: string;
            meaning?: components["schemas"]["VocabMeaning"];
        };
        /**
         * @example {
         *       "id": 1,
         *       "key": "lesson-01",
         *       "book": 1,
         *       "wordCount": 47
         *     }
         */
        VocabLessonSummary: {
            /** @description Lesson number (1–50 cho Minna, 1–3 cho Numbers) */
            id?: number;
            key?: string;
            book?: number | null;
            wordCount?: number;
        };
        VocabLessonDetail: components["schemas"]["VocabLessonSummary"] & {
            words?: components["schemas"]["VocabWord"][];
        };
        /**
         * @example {
         *       "lessonId": 1,
         *       "exerciseType": "meaning-quiz",
         *       "score": 10,
         *       "total": 12,
         *       "answers": [
         *         {
         *           "wordIndex": 1,
         *           "userAnswer": "tôi",
         *           "correct": true
         *         },
         *         {
         *           "wordIndex": 2,
         *           "userAnswer": "anh",
         *           "correct": true
         *         },
         *         {
         *           "wordIndex": 5,
         *           "userAnswer": "thầy",
         *           "correct": false
         *         }
         *       ]
         *     }
         */
        SubmitVocabAttemptInput: {
            lessonId: number;
            /** @enum {string} */
            exerciseType: "flashcard" | "meaning-quiz" | "reading-quiz" | "typing-quiz" | "matching";
            score: number;
            total: number;
            answers: {
                wordIndex: number;
                userAnswer: string;
                correct: boolean;
            }[];
        };
        VocabWeakWord: {
            wordIndex?: number;
            lessonId?: number;
            kanji?: string | null;
            kana?: string;
            romaji?: string;
            meaning?: components["schemas"]["VocabMeaning"];
            correctCount?: number;
            attemptCount?: number;
            accuracy?: number;
        };
        /**
         * @example {
         *       "attemptId": "33445566-7788-99aa-bbcc-ddeeff001122",
         *       "score": 10,
         *       "total": 12,
         *       "accuracy": 83.3,
         *       "weakWords": [
         *         {
         *           "wordIndex": 5,
         *           "kanji": "先生",
         *           "kana": "せんせい",
         *           "romaji": "sensei",
         *           "meaning": {
         *             "en": "teacher",
         *             "fr": "professeur",
         *             "vi": "thầy/cô giáo"
         *           }
         *         }
         *       ]
         *     }
         */
        VocabAttemptResult: {
            /** Format: uuid */
            attemptId?: string;
            score?: number;
            total?: number;
            accuracy?: number;
            weakWords?: {
                wordIndex?: number;
                kanji?: string | null;
                kana?: string;
                romaji?: string;
                meaning?: components["schemas"]["VocabMeaning"];
            }[];
        };
        /**
         * @example {
         *       "summary": {
         *         "totalLessons": 50,
         *         "practicedLessons": 12,
         *         "totalWords": 2692,
         *         "masteredWords": 420,
         *         "masteryPercent": 15.6,
         *         "totalAttempts": 34
         *       },
         *       "perLesson": [
         *         {
         *           "lessonId": 1,
         *           "totalWords": 47,
         *           "masteredWords": 40,
         *           "masteryPercent": 85.1,
         *           "practicedWords": 47
         *         },
         *         {
         *           "lessonId": 2,
         *           "totalWords": 52,
         *           "masteredWords": 30,
         *           "masteryPercent": 57.7,
         *           "practicedWords": 50
         *         }
         *       ],
         *       "weakWords": [
         *         {
         *           "lessonId": 1,
         *           "wordIndex": 5,
         *           "kanji": "先生",
         *           "kana": "せんせい",
         *           "romaji": "sensei",
         *           "meaning": {
         *             "en": "teacher",
         *             "fr": "professeur",
         *             "vi": "thầy/cô giáo"
         *           },
         *           "correctCount": 1,
         *           "attemptCount": 5,
         *           "accuracy": 20
         *         }
         *       ],
         *       "recentAttempts": [
         *         {
         *           "id": "11..",
         *           "lessonId": 1,
         *           "exerciseType": "meaning-quiz",
         *           "score": 10,
         *           "total": 12,
         *           "attemptedAt": "2026-04-24T10:30:00Z"
         *         },
         *         {
         *           "id": "22..",
         *           "lessonId": 2,
         *           "exerciseType": "typing-quiz",
         *           "score": 8,
         *           "total": 10,
         *           "attemptedAt": "2026-04-23T20:15:00Z"
         *         }
         *       ]
         *     }
         */
        VocabProgress: {
            summary?: {
                totalLessons?: number;
                practicedLessons?: number;
                totalWords?: number;
                masteredWords?: number;
                masteryPercent?: number;
                totalAttempts?: number;
            };
            perLesson?: {
                lessonId?: number;
                totalWords?: number;
                masteredWords?: number;
                masteryPercent?: number;
                practicedWords?: number;
            }[];
            weakWords?: components["schemas"]["VocabWeakWord"][];
            recentAttempts?: {
                /** Format: uuid */
                id?: string;
                lessonId?: number;
                exerciseType?: string;
                score?: number;
                total?: number;
                /** Format: date-time */
                attemptedAt?: string;
            }[];
        };
    };
    responses: {
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"] & unknown;
            };
        };
        /** @description Lesson Not Found */
        LessonNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"] & unknown;
            };
        };
        /** @description Sai mật khẩu */
        InvalidPassword: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"] & unknown;
            };
        };
        /** @description Sai email hoặc mật khẩu */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"] & unknown;
            };
        };
        /** @description Input không hợp lệ */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"] & unknown;
            };
        };
        /** @description Slug đã tồn tại */
        SlugConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"] & unknown;
            };
        };
    };
    parameters: {
        LocaleQuery: "en" | "vi" | "ja" | "fr";
        IdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
